//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETOS_INCIDENCIAS
    {
        public long PK1 { get; set; }
        public long PK_SORTEO { get; set; }
        public long PK_TALONARIO { get; set; }
        public string TALONARIO { get; set; }
        public long PK_BOLETO { get; set; }
        public string BOLETO { get; set; }
        public string FORMATO { get; set; }
        public string INCIDENCIA { get; set; }
        public string FOLIOMP { get; set; }
        public string DETALLES { get; set; }
        public Nullable<long> PK_SECTOR { get; set; }
        public Nullable<long> PK_NICHO { get; set; }
        public Nullable<long> PK_COLABORADOR { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA_R { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
    }
}
