//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOLETO()
        {
            this.COLABORADORES_BOLETOS = new HashSet<SORTEOS_COLABORADORES_BOLETOS>();
            this.COMPRADORES = new HashSet<COMPRADORE>();
        }
    
        public long PK1 { get; set; }
        public string FOLIO { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public int SORTEO { get; set; }
        public string FORMATO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_R { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
        public bool ASIGNADO { get; set; }
        public string VENDIDO { get; set; }
        public Nullable<decimal> ABONO { get; set; }
        public long PK_TALONARIO { get; set; }
        public Nullable<bool> RETORNADO { get; set; }
        public string INCIDENCIA { get; set; }
        public string TALONARIO { get; set; }
        public Nullable<int> FOLIODIGITAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORTEOS_COLABORADORES_BOLETOS> COLABORADORES_BOLETOS { get; set; }
        public virtual TALONARIO TALONARIO_REL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRADORE> COMPRADORES { get; set; }
    }
}
