//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLABORADORE()
        {
            this.CORREOS = new HashSet<COLABORADORES_CORREOS>();
            this.COLABORADORES_TALONARIOS = new HashSet<SORTEOS_COLABORADORES_TALONARIOS>();
            this.COLABORADORES_BOLETOS = new HashSet<SORTEOS_COLABORADORES_BOLETOS>();
            this.COLABORADORES_BITACORA_ACCESO = new HashSet<COLABORADORES_BITACORA_ACCESO>();
        }
    
        public long PK1 { get; set; }
        public string CLAVE { get; set; }
        public string NOMBRE { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public Nullable<decimal> COMISION { get; set; }
        public string RFC { get; set; }
        public string EDAD { get; set; }
        public string REFBANCARIA { get; set; }
        public string SECTOR { get; set; }
        public string DESCRIPCION { get; set; }
        public long PK_SORTEO { get; set; }
        public long PK_NICHO { get; set; }
        public long PK_USUARIO { get; set; }
        public System.DateTime FECHA_R { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
        public bool ELIMINADO { get; set; }
        public decimal ABONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLABORADORES_CORREOS> CORREOS { get; set; }
        public virtual NICHO NICHO { get; set; }
        public virtual SORTEO SORTEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORTEOS_COLABORADORES_TALONARIOS> COLABORADORES_TALONARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORTEOS_COLABORADORES_BOLETOS> COLABORADORES_BOLETOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLABORADORES_BITACORA_ACCESO> COLABORADORES_BITACORA_ACCESO { get; set; }
    }
}
