//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRADORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRADORE()
        {
            this.GANADORES = new HashSet<GANADORE>();
        }
    
        public long PK1 { get; set; }
        public long PK_SORTEO { get; set; }
        public long PK_TALONARIO { get; set; }
        public string TALONARIO { get; set; }
        public long PK_BOLETO { get; set; }
        public string BOLETO { get; set; }
        public Nullable<decimal> ABONO { get; set; }
        public Nullable<long> PK_SECTOR { get; set; }
        public Nullable<long> PK_NICHO { get; set; }
        public Nullable<long> PK_COLABORADOR { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string TELEFONOF { get; set; }
        public string TELEFONOM { get; set; }
        public string CORREO { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string COLONIA { get; set; }
        public string ESTADO { get; set; }
        public string MUNDEL { get; set; }
        public bool GANADOR { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA_R { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
        public string CP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GANADORE> GANADORES { get; set; }
        public virtual BOLETO BOLETO_REL { get; set; }
    }
}
