//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREMIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREMIO()
        {
            this.GANADOR = new HashSet<GANADORE>();
        }
    
        public long PK1 { get; set; }
        public long PK_SORTEO { get; set; }
        public int NUM_PREMIO { get; set; }
        public int CLASIFICACION { get; set; }
        public string NOMBRE { get; set; }
        public decimal VALOR { get; set; }
        public int ESTRELLAS { get; set; }
        public string DESCRIPCION { get; set; }
        public string IMAGEN { get; set; }
        public System.DateTime FECHA_R { get; set; }
        public string USUARIO { get; set; }
        public int CLAVE_BENEFICIARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GANADORE> GANADOR { get; set; }
    }
}
