//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLE()
        {
            this.USUARIOS = new HashSet<ROLES_USUARIO>();
            this.PERMISOS = new HashSet<vPermiso>();
        }
    
        public long PK1 { get; set; }
        public string ROLE1 { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA_R { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
        public Nullable<bool> ELIMINADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLES_USUARIO> USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vPermiso> PERMISOS { get; set; }
    }
}
