//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sorteo2016Entities : DbContext
    {
        public Sorteo2016Entities()
            : base("name=Sorteo2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COLABORADORE> COLABORADORES { get; set; }
        public virtual DbSet<COLABORADORES_CORREOS> COLABORADORES_CORREOS { get; set; }
        public virtual DbSet<COMPRADORE> COMPRADORES { get; set; }
        public virtual DbSet<GANADORE> GANADORES { get; set; }
        public virtual DbSet<NICHO> NICHOS { get; set; }
        public virtual DbSet<PREMIO> PREMIOS { get; set; }
        public virtual DbSet<SORTEOS_ASIGNACION_COLABORADORES> SORTEOS_ASIGNACION_COLABORADORES { get; set; }
        public virtual DbSet<SORTEOS_ASIGNACION_NICHOS> SORTEOS_ASIGNACION_NICHOS { get; set; }
        public virtual DbSet<SORTEOS_ASIGNACION_SECTORES> SORTEOS_ASIGNACION_SECTORES { get; set; }
        public virtual DbSet<SORTEOS_NICHOS_BOLETOS> SORTEOS_NICHOS_BOLETOS { get; set; }
        public virtual DbSet<SORTEOS_NICHOS_TALONARIOS> SORTEOS_NICHOS_TALONARIOS { get; set; }
        public virtual DbSet<SORTEOS_SECTORES_BOLETOS> SORTEOS_SECTORES_BOLETOS { get; set; }
        public virtual DbSet<SORTEOS_SECTORES_TALONARIOS> SORTEOS_SECTORES_TALONARIOS { get; set; }
        public virtual DbSet<BOLETOS_INCIDENCIAS> BOLETOS_INCIDENCIAS { get; set; }
        public virtual DbSet<SORTEO> SORTEOS { get; set; }
        public virtual DbSet<SORTEOS_BOLETOS> SORTEOS_BOLETOS { get; set; }
        public virtual DbSet<SORTEOS_TALONARIOS> SORTEOS_TALONARIOS { get; set; }
        public virtual DbSet<SORTEOS_COLABORADORES_BOLETOS> SORTEOS_COLABORADORES_BOLETOS { get; set; }
        public virtual DbSet<SORTEOS_COLABORADORES_TALONARIOS> SORTEOS_COLABORADORES_TALONARIOS { get; set; }
        public virtual DbSet<BOLETO_TAB> BOLETOS { get; set; }
        public virtual DbSet<SECTORE> SECTORES { get; set; }
        public virtual DbSet<TALONARIO> TALONARIOS { get; set; }
        public virtual DbSet<BOLETO> vBoletos { get; set; }
        public virtual DbSet<ESTADO_CUENTA> ESTADO_CUENTA { get; set; }
        public virtual DbSet<SEPOMEX> SEPOMEXes { get; set; }
        public virtual DbSet<PERMISO> PERMISOS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<ROLES_USUARIO> ROLES_USUARIO { get; set; }
        public virtual DbSet<SORTEOS_USUARIOS_NICHOS> SORTEOS_USUARIOS_NICHOS { get; set; }
        public virtual DbSet<SORTEOS_USUARIOS_SECTORES> SORTEOS_USUARIOS_SECTORES { get; set; }
        public virtual DbSet<USUARIOS_CORREOS> USUARIOS_CORREOS { get; set; }
        public virtual DbSet<SORTEOS_USUARIOS> SORTEOS_USUARIOS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<vPermiso> vPermisos { get; set; }
        public virtual DbSet<COLABORADORES_BITACORA_ACCESO> COLABORADORES_BITACORA_ACCESO { get; set; }
    }
}
