//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SORTEO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SORTEO()
        {
            this.COLABORADORES = new HashSet<COLABORADORE>();
            this.GANADORES = new HashSet<GANADORE>();
        }
    
        public long PK1 { get; set; }
        public string CLAVE { get; set; }
        public string SORTEO1 { get; set; }
        public string DESCRIPCION { get; set; }
        public string IMAGEN { get; set; }
        public System.DateTime FECHA_I { get; set; }
        public System.DateTime FECHA_T { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<long> PK_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_R { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
        public Nullable<bool> ELIMINADO { get; set; }
        public Nullable<bool> CARGA { get; set; }
        public string CUENTA_DEPOSITO { get; set; }
        public string URL_1 { get; set; }
        public string URL_2 { get; set; }
        public string URL_3 { get; set; }
        public string URL_4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLABORADORE> COLABORADORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GANADORE> GANADORES { get; set; }
    }
}
