//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TALONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TALONARIO()
        {
            this.COLABORADORES_TALONARIOS = new HashSet<SORTEOS_COLABORADORES_TALONARIOS>();
            this.BOLETOS = new HashSet<BOLETO>();
        }
    
        public long PK1 { get; set; }
        public string FOLIO { get; set; }
        public int NUMBOLETOS { get; set; }
        public Nullable<int> SORTEO { get; set; }
        public string FORMATO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_R { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
        public bool ASIGNADO { get; set; }
        public string VENDIDO { get; set; }
        public Nullable<decimal> ABONO { get; set; }
        public Nullable<bool> DIGITAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORTEOS_COLABORADORES_TALONARIOS> COLABORADORES_TALONARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLETO> BOLETOS { get; set; }
    }
}
