//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ROLES = new HashSet<ROLES_USUARIO>();
        }
    
        public long PK1 { get; set; }
        public string USUARIO1 { get; set; }
        public string PASSWORD { get; set; }
        public string NOMBRE { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string IMAGEN { get; set; }
        public string RFC { get; set; }
        public string EDAD { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<long> PK_USUARIO { get; set; }
        public System.DateTime FECHA_R { get; set; }
        public Nullable<System.DateTime> FECHA_M { get; set; }
        public Nullable<bool> ELIMINADO { get; set; }
        public Nullable<int> PK_SORTEO { get; set; }
        public Nullable<int> PK_SECTOR { get; set; }
        public Nullable<int> PK_NICHO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLES_USUARIO> ROLES { get; set; }
    }
}
