//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorteoAnahuac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPermiso
    {
        public int PK1 { get; set; }
        public Nullable<long> PK_ROL { get; set; }
        public Nullable<long> PK_PERMISO { get; set; }
    
        public virtual PERMISO PERMISO { get; set; }
        public virtual ROLE ROL { get; set; }
    }
}
